### ISSUE TITLE
sbnobj incompatible with latest sbncode

### ISSUE THREAD

**Issue by cjbackhouse** [SBNSoftware/sbnobj#3]
Trying to setup sbnobj in the same area as sbncode v08_47_00 (the current latest) I get

`ERROR: Version conflict -- dependency tree requires versions conflicting with current setup of product cetbuildtools: version v7_15_01 vs v7_13_02`

Is the right solution to make a new release of sncode based on more recent versions?

**Comment by PetrilloAtWork** [comment]
I also think the solution involves an update in `sbncode`, and I have opened an issue SBNSoftware/sbncode#11 on the matter.

**Comment by PetrilloAtWork** [comment]
Branch `feature/repositoryRestructuring` of `sbnobj` and `sbncode` (and `sbndcode` and `icaruscode`) should be compatible.

**Comment by wesketchum** [comment]
I believe we have this all fixed now. Closing.
